Dev
NRothera/sparta-project1-jsgame pull request #1
Opened 2017-11-07 18:17 UTC by NRothera

2017-11-07 23:33 UTC, JSChilds commented on css/styles.css
> +/*#bomberman2{
Don't leave commented-out code in a project you are submitting as finished.

2017-11-07 23:33 UTC, JSChilds commented on js/player2.js
> +// var currentKey2;
Don't include files in the file system that you aren't using as part of this delivered version.

2017-11-07 23:34 UTC, JSChilds requested changes
Remove the commented-out code and unused player2.js file and you will be ready to merge.

2017-11-08 07:15 UTC, NRothera commented
Yeah sorry I saw he said that after I submitted it! My bad

On 7 Nov 2017 23:34, "JSChilds" <notifications@github.com> wrote:

> *@JSChilds* requested changes on this pull request.
>
> Remove the commented-out code and unused player2.js file and you will be
> ready to merge.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NRothera/sparta-project1-jsgame/pull/1#pullrequestreview-74947260>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AeA7T2_Z6LkdjZ2GsDeSPlC65abk30G3ks5s0Oj6gaJpZM4QVOi1>
> .
>

2017-11-08 11:49 UTC, j-mcgregor approved these changes
Very clean, well done

2017-11-08 12:12 UTC, JSChilds approved these changes

2017-11-08 13:16 UTC, merged